blockchains:
- name: ronin
  contract: "0xc99a6a985ed2cac1ef41640596c5a5f9f4e19ef5"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x267083B"
  end_block: "0x2670A2E"
  rpcs:
  - "https://ronin.lgns.net/rpc"
  - "https://ronin.drpc.org"
  - "https://api.roninchain.com/rpc"

- name: arbitrum
  contract: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x10AE6A39"
  end_block: "0x10AE7209"
  rpcs:
  #- "https://arbitrum.llamarpc.com"
  #- "https://endpoints.omniatech.io/v1/arbitrum/one/public"
  - "https://arb1.arbitrum.io/rpc"
  - "https://arbitrum-one.publicnode.com"
  - "https://arbitrum.drpc.org"
  #- "https://rpc.ankr.com/arbitrum"
  - "https://arbitrum.gateway.tenderly.co"
  #- "https://endpoints.omniatech.io/v1/arbitrum/one/public"
  - "https://arb-pokt.nodies.app"
  - "https://arbitrum.meowrpc.com"   

- name: ethereum
  contract: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x1447000"
  end_block: "0x14478BC"
  rpcs:
  - "https://ethereum-rpc.publicnode.com"
  - "https://mainnet.gateway.tenderly.co"
  - "https://rpc.flashbots.net"
  - "https://rpc.flashbots.net/fast"
  - "https://rpc.mevblocker.io"
  - "https://rpc.mevblocker.io/fast"
  - "https://rpc.mevblocker.io/noreverts"
  - "https://rpc.mevblocker.io/fullprivacy"

- name: gnosis
  contract: "0x8e5bBbb09Ed1ebdE8674Cda39A0c169401db4252"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x23804B2"
  end_block: "0x238C802"
  rpcs:
  - "https://rpc.gnosischain.com"
  - "https://rpc.gnosis.gateway.fm"
  - "https://gnosis.oat.farm"
  - "https://gnosis-rpc.publicnode.com"
  - "https://gnosis.drpc.org"
  - "https://gnosis-mainnet.public.blastapi.io"
  - "https://rpc.ap-southeast-1.gateway.fm/v4/gnosis/non-archival/mainnet"


- name: optimism
  contract: "0x4200000000000000000000000000000000000006"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x7AB7B45"
  end_block: "0x7AB8315"
  rpcs:
  #- "https://optimism.llamarpc.com"
  #- "https://optimism.blockpi.network/v1/rpc/public"
  - "https://optimism-rpc.publicnode.com"
  - "https://optimism.gateway.tenderly.co"
  #- "https://optimism.drpc.org"
  #- "https://optimism-mainnet.public.blastapi.io"
  #- "https://1rpc.io/op"
  #- "https://rpc.ankr.com/optimism"

- name: polygon
  contract: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x30B2ADB"
  end_block: "0x30B32AB"
  rpcs:
  - "https://rpc-mainnet.matic.quiknode.pro"
  - "https://polygon.gateway.tenderly.co"
  #- "https://polygon-mainnet.public.blastapi.io"
  #- "https://polygon.blockpi.network/v1/rpc/public"
  #- "https://1rpc.io/matic"
  # - "https://polygon-rpc.com/" # This RPC is unreliable and often down / returns inconsistent results
  # - "https://polygon.drpc.org" # This RPC is unreliable and often down / returns inconsistent results
  # - "https://rpc.ankr.com/polygon" # This RPC is unreliable and often down / returns inconsistent results
  # - "https://polygon.api.onfinality.io/public" # This RPC is unreliable and often down / returns inconsistent results
  # - "https://polygon.rpc.subquery.network/public" # This RPC is unreliable and often down / returns inconsistent results
  # - "https://polygon.meowrpc.com" # This RPC is unreliable and often down / returns inconsistent results

- name: base
  contract: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x1610B43"
  end_block: "0x1611313"
  rpcs:
  #- "https://base.llamarpc.com"
  #- "https://rpc.numa.network/base"
  - "https://mainnet.base.org"
  #- "https://base-mainnet.public.blastapi.io"
  - "https://base-rpc.publicnode.com"
  - "https://base.drpc.org"
  - "https://base.api.onfinality.io/public"
  - "https://base.lava.build"
  - "https://1rpc.io/base"
  # Optional provider-backed endpoints (require API keys):
  # - "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_BASE_KEY}"
  # - "https://base-mainnet.infura.io/v3/${INFURA_KEY}"

- name: bnb
  contract: "0xBA5Fe23f8a3a24BEd3236F05F2FcF35fd0BF0B5C"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x2AA9AC8"
  end_block: "0x2AA9EB0"
  rpcs:
  #- "https://bsc.rpc.blxrbdn.com"
  #- "https://bsc-mainnet.public.blastapi.io"
  - "https://bsc-pokt.nodies.app"
  #- "https://bsc.blockrazor.xyz"
  #- "https://rpc-bsc.48.club"
  - "https://bsc.meowrpc.com"
  #- "https://api.zan.top/bsc-mainnet"
  - "https://bnb.api.onfinality.io/public"
  - "https://1rpc.io/bnb"
  #- "https://binance.nodereal.io"
  #- "https://bsc-rpc.publicnode.com"
  - "https://bsc.drpc.org"
  - "https://binance.llamarpc.com"

- name: avalanche
  contract: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0x33c1898"
  end_block: "0x33c2068"
  rpcs:
  #- "https://1rpc.io/avax/c"
  #- "https://avalanche.public-rpc.com"
  - "https://avalanche-c-chain-rpc.publicnode.com"
  #- "https://rpc.ankr.com/avalanche"
  - "https://avalanche.drpc.org"
  - "https://avalanche-mainnet.gateway.tenderly.co"

- name: scroll
  contract: "0x06efdbff2a14a7c8e15944d1f4a48f9f95f663a4"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0xAE926E"
  end_block: "0xAE9A3E"
  rpcs:
  - "https://scroll.drpc.org"
  - "https://scroll-rpc.publicnode.com"
  - "https://rpc.scroll.io"
  - "https://scroll-mainnet.public.blastapi.io"
  - "https://scroll-mainnet-public.unifra.io"
  - "https://endpoints.omniatech.io/v1/scroll/mainnet/public"
  - "https://rpc.ankr.com/scroll"

- name: linea
  contract: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff"
  topics:
  - "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
  start_block: "0xC8FA38"
  end_block: "0xC90208"
  rpcs:
  - "https://linea.drpc.org"
  - "https://linea-rpc.publicnode.com"
  - "https://1rpc.io/linea"
  - "https://rpc.linea.build"

- name: solana
  rpcs:
  - "https://api.mainnet-beta.solana.com"